-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: 4c90c9557da7c0d695d6a729bae8b1de4e496cbf
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-json
    -   id: check-merge-conflict
-   repo: git://github.com/magicmark/pre-commit-es6-imports-reorder
    sha: 9ca7b2274eef5355d550b6cb7e2cd5e9ee518d2f
    hooks:
    -   id: reorder-es6-imports
-   repo: local
    hooks:
    -   id: eslint
        name: eslint
        entry: node_modules/.bin/eslint
        language: node
        files: \.js$
